---
# tasks_include for keybase_unseal by @bbaassssiiee

- name: 'seal Hashicorp Vault with --tags=seal -e seal=true'
  no_log: true
  when: seal is defined
  environment:
    VAULT_ADDR: "https://{{ groups.vault_instances[0] }}:{{ vault_port }}"
    VAULT_CACERT: "{{ vault_tls_config_path }}/{{ vault_tls_ca_file }}"
    VAULT_TOKEN: "{{ root_token }}"
  command: "vault operator seal"
  tags:
    - seal

...
